### ISSUE TITLE
AssertionError: Bad argument number for Name: 3, expecting 4

### ISSUE THREAD

**Issue by pranavkr29** [tensorflow/autograph#1]
I was trying to first run this model : [https://www.tensorflow.org/beta/tutorials/generative/cvae](url) to see how it works. This was the error it gave when i try to get predictions:

`TypeError                                 Traceback (most recent call last)
<ipython-input-48-4f851706bc88> in <module>
----> 1 generate_and_save_images(model, 0, random_vector_for_generation)
      2 
      3 for epoch in range(1, epochs + 1):
      4   start_time = time.time()
      5   for train_x in train_dataset:

<ipython-input-47-68d3e35cc197> in generate_and_save_images(model, epoch, test_input)
      5   for i in range(predictions.shape[0]):
      6       plt.subplot(4, 4, i+1)
----> 7       plt.imshow(predictions[i, :, :, 0], cmap='gray')
      8       plt.axis('off')
      9 

/opt/conda/lib/python3.6/site-packages/matplotlib/pyplot.py in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, data, **kwargs)
   2697         filternorm=filternorm, filterrad=filterrad, imlim=imlim,
   2698         resample=resample, url=url, **({"data": data} if data is not
-> 2699         None else {}), **kwargs)
   2700     sci(__ret)
   2701     return __ret

/opt/conda/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1808                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1809                         RuntimeWarning, stacklevel=2)
-> 1810             return func(ax, *args, **kwargs)
   1811 
   1812         inner.__doc__ = _add_data_doc(inner.__doc__,

/opt/conda/lib/python3.6/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5492                               resample=resample, **kwargs)
   5493 
-> 5494         im.set_data(X)
   5495         im.set_alpha(alpha)
   5496         if im.get_clip_path() is None:

/opt/conda/lib/python3.6/site-packages/matplotlib/image.py in set_data(self, A)
    632         if (self._A.dtype != np.uint8 and
    633                 not np.can_cast(self._A.dtype, float, "same_kind")):
--> 634             raise TypeError("Image data cannot be converted to float")
    635 
    636         if not (self._A.ndim == 2

TypeError: Image data cannot be converted to float`

There was another warning just on top of this one: 
WARNING: Entity <bound method CVAE.sample of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f59d2b0ada0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method CVAE.sample of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f59d2b0ada0>>: AssertionError: Bad argument number for Name: 3, expecting 4

I've run this on my PC and Kaggle, and it gives the same error at both places.

**Comment by AnirudhPenmatcha** [comment]
Not sure what the bug is exactly. But installing installing gast 0.2.2 version fixed it. 

pip install --user gast==0.2.2

**Comment by mdanatg** [comment]
Sorry for the delay! Yes, this is due to a breaking version in gast. Newer versions of TF pin it to 0.2.2 until we have the chance to upgrade the code.
