### ISSUE TITLE
<function preprocess_time at 0x7fed4c4e9048> could not be transformed 

### ISSUE THREAD

**Issue by le-dawg** [tensorflow/autograph#8]
> WARNING:tensorflow:Entity <function preprocess_time at 0x7fed4c4e9048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4

This happens at the very beginning of my runs and doesn't immediately lead to errors.:

`INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c47160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 10 or save_checkpoints_secs None.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c476a0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c476a0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING: Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From <ipython-input-15-270888898f76>:68: calling Subnetwork.__new__ (from adanet.subnetwork.generator) with persisted_tensors is deprecated and will be removed in a future version.
Instructions for updating:
`persisted_tensors` is deprecated, please use `shared` instead.
WARNING:tensorflow:From <ipython-input-15-270888898f76>:68: calling Subnetwork.__new__ (from adanet.subnetwork.generator) with persisted_tensors is depr`

**Comment by mdanatg** [comment]
This looks like a version mismatch in gast. Newer versions will install the correct version, but 2.0 installs the newest, which is not compatible. See [this comment](https://github.com/tensorflow/tensorflow/issues/38691#issuecomment-617897539).

Could you try either one of the following:
 * install TF 2.2, which should work with gast 0.3.3
 * install TF 2.1, which should install gast 0.2.2
 * if you wish to stay on TF 2.0, run `pip install gast==0.2.2 --force-reinstall`

**Comment by ghost** [comment]
> > WARNING:tensorflow:Entity <function preprocess_time at 0x7fed4c4e9048> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> 
> 
> 
> This happens at the very beginning of my runs and doesn't immediately lead to errors.:
> 
> 
> 
> `INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> 
> graph_options {
> 
>   rewrite_options {
> 
>     meta_optimizer_iterations: ONE
> 
>   }
> 
> }
> 
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c47160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
> 
> INFO:tensorflow:Not using Distribute Coordinator.
> 
> INFO:tensorflow:Running training and evaluation locally (non-distributed).
> 
> INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 10 or save_checkpoints_secs None.
> 
> INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> 
> graph_options {
> 
>   rewrite_options {
> 
>     meta_optimizer_iterations: ONE
> 
>   }
> 
> }
> 
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c476a0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
> 
> INFO:tensorflow:Using config: {'_model_dir': '/tmp/models/3simple_cnn', '_tf_random_seed': 42, '_save_summary_steps': 1, '_save_checkpoints_steps': 10, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> 
> graph_options {
> 
>   rewrite_options {
> 
>     meta_optimizer_iterations: ONE
> 
>   }
> 
> }
> 
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5019c476a0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
> 
> WARNING:tensorflow:Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> 
> WARNING:tensorflow:Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> 
> WARNING: Entity <function preprocess_time at 0x7f50693d4730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
> 
> INFO:tensorflow:Calling model_fn.
> 
> INFO:tensorflow:Calling model_fn.
> 
> WARNING:tensorflow:
> 
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> 
> For more information, please see:
> 
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
> 
>   * https://github.com/tensorflow/addons
> 
>   * https://github.com/tensorflow/io (for I/O related ops)
> 
> If you depend on functionality not listed there, please file an issue.
> 
> 
> 
> WARNING:tensorflow:
> 
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> 
> For more information, please see:
> 
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
> 
>   * https://github.com/tensorflow/addons
> 
>   * https://github.com/tensorflow/io (for I/O related ops)
> 
> If you depend on functionality not listed there, please file an issue.
> 
> 
> 
> WARNING:tensorflow:From <ipython-input-15-270888898f76>:68: calling Subnetwork.__new__ (from adanet.subnetwork.generator) with persisted_tensors is deprecated and will be removed in a future version.
> 
> Instructions for updating:
> 
> `persisted_tensors` is deprecated, please use `shared` instead.
> 
> WARNING:tensorflow:From <ipython-input-15-270888898f76>:68: calling Subnetwork.__new__ (from adanet.subnetwork.generator) with persisted_tensors is depr`
> 
> 
> 
>
